string1 = f'\nIngresar números decimales separados por un "."'
print(f'{string1}\n{'\u2500' * len(string1)}')


print('Elija la unidad de medida a convertir:\n')
print(
    '\033[1mMétrico:\033[0m nm - µm - mm - cm - m - km\n' +
    '\033[1mImperial:\033[0m in - ft - yd - mi\n'
)
medida = input('Ingrese medida: ')
valor = float(input('Valor: '))
print('')


if medida == 'nm':
    print(f'{valor} {medida} ➜ {valor * 0.001} µm')
    print(f'{valor} {medida} ➜ {(valor * (10**-6)):.6f} mm')
    print(f'{valor} {medida} ➜ {(valor * (10**-7)):.7f} cm')
    print(f'{valor} {medida} ➜ {(valor * (10**-9)):.9f} m')
    print(f'{valor} {medida} ➜ {(valor * (10**-12)):.12f} km')
    print('')
    print(f'{valor} {medida} ➜ {((valor * 3.937) * (10**-8)):.11f} in')
    print(f'{valor} {medida} ➜ {((valor * 3.281) * (10**-9)):.12f} ft')
    print(f'{valor} {medida} ➜ {((valor * 1.094) * (10**-9)):.12f} yd')
    print(f'{valor} {medida} ➜ {((valor * 6.214) * (10**-13)):.16f} mi')
elif medida == 'µm':
    print(f'{valor} {medida} ➜ {valor * 1000} nm')
    print(f'{valor} {medida} ➜ {valor * 0.001} mm')
    print(f'{valor} {medida} ➜ {(valor * (10**-4)):.4f} cm')
    print(f'{valor} {medida} ➜ {(valor * (10**-6)):.6f} m')
    print(f'{valor} {medida} ➜ {(valor * (10**-9)):.9f} km')
    print('')
    print(f'{valor} {medida} ➜ {((valor * 3.937) * (10**-5)):.8f} in')
    print(f'{valor} {medida} ➜ {((valor * 3.281) * (10**-6)):.9f} ft')
    print(f'{valor} {medida} ➜ {((valor * 1.094) * (10**-6)):.9f} yd')
    print(f'{valor} {medida} ➜ {((valor * 6.214) * (10**-10)):.13f} mi')
elif medida == 'mm':
    print(f'{valor} {medida} ➜ {valor * (10**6)} nm')
    print(f'{valor} {medida} ➜ {valor * 1000} µm')
    print(f'{valor} {medida} ➜ {valor * 0.1} cm')
    print(f'{valor} {medida} ➜ {valor * 0.001} m')
    print(f'{valor} {medida} ➜ {(valor * (10**-6)):.6f} km')
    print('')
    print(f'{valor} {medida} ➜ {((valor * 3.937) * (10**-5)):.8f} in')
    print(f'{valor} {medida} ➜ {((valor * 3.281) * (10**-6)):.9f} ft')
    print(f'{valor} {medida} ➜ {((valor * 1.094) * (10**-6)):.9f} yd')
    print(f'{valor} {medida} ➜ {((valor * 6.214) * (10**-10)):.13f} mi')
elif medida == 'cm':
    print(f'{valor} {medida} ➜ {valor * (10**7)} nm')
    print(f'{valor} {medida} ➜ {valor * 10000} µm')
    print(f'{valor} {medida} ➜ {valor * 10} mm')
    print(f'{valor} {medida} ➜ {valor * 0.01} m')
    print(f'{valor} {medida} ➜ {(valor * (10**-5)):.5f} km')
    print('')
    print(f'{valor} {medida} ➜ {valor * 0.3937} in')
    print(f'{valor} {medida} ➜ {valor * 0.03281} ft')
    print(f'{valor} {medida} ➜ {valor * 0.01094} yd')
    print(f'{valor} {medida} ➜ {((valor * 6.214) * (10**-6)):.9f} mi')
elif medida == 'm':
    print(f'{valor} {medida} ➜ {valor * (10**9)} nm')
    print(f'{valor} {medida} ➜ {valor * (10**6)} µm')
    print(f'{valor} {medida} ➜ {valor * 1000} mm')
    print(f'{valor} {medida} ➜ {valor * 100} cm')
    print(f'{valor} {medida} ➜ {valor * 0.001} km')
    print('')
    print(f'{valor} {medida} ➜ {valor * 39.37} in')
    print(f'{valor} {medida} ➜ {valor * 3.281} ft')
    print(f'{valor} {medida} ➜ {valor * 1.094} yd')
    print(f'{valor} {medida} ➜ {((valor * 6.214) * (10**-4)):.7f} mi')
elif medida == 'km':
    print(f'{valor} {medida} ➜ {valor * (10**12)} nm')
    print(f'{valor} {medida} ➜ {valor * (10**9)} µm')
    print(f'{valor} {medida} ➜ {valor * (10**6)} mm')
    print(f'{valor} {medida} ➜ {valor * 100000} cm')
    print(f'{valor} {medida} ➜ {valor * 1000} m')
    print('')
    print(f'{valor} {medida} ➜ {valor * 39370} in')
    print(f'{valor} {medida} ➜ {valor * 3281} ft')
    print(f'{valor} {medida} ➜ {valor * 1094} yd')
    print(f'{valor} {medida} ➜ {valor * 0.6214} mi')
elif medida == 'in':
    print(f'{valor} {medida} ➜ {((valor * 2.54) * (10**7))} nm')
    print(f'{valor} {medida} ➜ {valor * 25400} µm')
    print(f'{valor} {medida} ➜ {valor * 25.4} mm')
    print(f'{valor} {medida} ➜ {valor * 2.54} cm')
    print(f'{valor} {medida} ➜ {valor * 0.0254} m')
    print(f'{valor} {medida} ➜ {((valor * 2.54) * (10**-5)):.7f} km')
    print('')
    print(f'{valor} {medida} ➜ {valor * 0.08333} ft')
    print(f'{valor} {medida} ➜ {valor * 0.02778} yd')
    print(f'{valor} {medida} ➜ {((valor * 1.578) * (10**-5)):.8f} mi')
elif medida == 'ft':
    print(f'{valor} {medida} ➜ {((valor * 3.048) * (10**8))} nm')
    print(f'{valor} {medida} ➜ {valor * 304800} µm')
    print(f'{valor} {medida} ➜ {valor * 304.8} mm')
    print(f'{valor} {medida} ➜ {valor * 30.48} cm')
    print(f'{valor} {medida} ➜ {valor * 0.3048} m')
    print(f'{valor} {medida} ➜ {((valor * 3.048) * (10**-4)):.7f} km')
    print('')
    print(f'{valor} {medida} ➜ {valor * 12} in')
    print(f'{valor} {medida} ➜ {valor * 0.3333} yd')
    print(f'{valor} {medida} ➜ {((valor * 1.894) * (10**-4)):.7f} mi')
elif medida == 'yd':
    print(f'{valor} {medida} ➜ {((valor * 9.144) * (10**8))} nm')
    print(f'{valor} {medida} ➜ {valor * 914400} µm')
    print(f'{valor} {medida} ➜ {valor * 914.4} mm')
    print(f'{valor} {medida} ➜ {valor * 91.44} cm')
    print(f'{valor} {medida} ➜ {valor * 0.9144} m')
    print(f'{valor} {medida} ➜ {((valor * 9.144) * (10**-4)):.7f} km')
    print('')
    print(f'{valor} {medida} ➜ {valor * 36} in')
    print(f'{valor} {medida} ➜ {valor * 3} ft')
    print(f'{valor} {medida} ➜ {((valor * 5.682) * (10**-4)):.7f} mi')
elif medida == 'mi':
    print(f'{valor} {medida} ➜ {((valor * 1.609) * (10**12))} nm')
    print(f'{valor} {medida} ➜ {((valor * 1.609) * (10**9))} µm')
    print(f'{valor} {medida} ➜ {((valor * 1.609) * (10**6))} mm')
    print(f'{valor} {medida} ➜ {valor * 160934} cm')
    print(f'{valor} {medida} ➜ {valor * 1609} m')
    print(f'{valor} {medida} ➜ {valor * 1.609} km')
    print('')
    print(f'{valor} {medida} ➜ {valor * 63360} in')
    print(f'{valor} {medida} ➜ {valor * 5280} ft')
    print(f'{valor} {medida} ➜ {valor * 1760} yd')